# Generated by Django 5.1.5 on 2025-06-13 03:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, help_text="Nom de l'icône pour l'interface", max_length=50)),
            ],
            options={
                'verbose_name': 'Type de machine',
                'verbose_name_plural': 'Types de machines',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text='Nom de la machine', max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100, unique=True)),
                ('numero_inventaire', models.CharField(blank=True, max_length=50, unique=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('maintenance', 'En maintenance'), ('hors_service', 'Hors service'), ('retire', 'Retiré')], default='actif', max_length=20)),
                ('date_achat', models.DateField(blank=True, null=True)),
                ('date_mise_service', models.DateField(blank=True, null=True)),
                ('date_fin_garantie', models.DateField(blank=True, null=True)),
                ('marque', models.CharField(blank=True, max_length=50)),
                ('modele', models.CharField(blank=True, max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('derniere_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('commentaires', models.TextField(blank=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='users.site')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='users.structure')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to=settings.AUTH_USER_MODEL)),
                ('type_machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.typemachine')),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='InformationSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_nom', models.CharField(blank=True, max_length=100)),
                ('os_version', models.CharField(blank=True, max_length=100)),
                ('os_architecture', models.CharField(blank=True, max_length=20)),
                ('os_build', models.CharField(blank=True, max_length=50)),
                ('cpu_nom', models.CharField(blank=True, max_length=200)),
                ('cpu_architecture', models.CharField(blank=True, max_length=20)),
                ('cpu_coeurs', models.IntegerField(blank=True, null=True)),
                ('cpu_threads', models.IntegerField(blank=True, null=True)),
                ('cpu_frequence', models.FloatField(blank=True, help_text='Fréquence en GHz', null=True)),
                ('ram_totale', models.BigIntegerField(blank=True, help_text='RAM totale en bytes', null=True)),
                ('ram_disponible', models.BigIntegerField(blank=True, help_text='RAM disponible en bytes', null=True)),
                ('stockage_total', models.BigIntegerField(blank=True, help_text='Stockage total en bytes', null=True)),
                ('stockage_libre', models.BigIntegerField(blank=True, help_text='Stockage libre en bytes', null=True)),
                ('nom_machine', models.CharField(blank=True, max_length=100)),
                ('domaine', models.CharField(blank=True, max_length=100)),
                ('date_collecte', models.DateTimeField(auto_now=True)),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_systeme', to='machines.machine')),
            ],
            options={
                'verbose_name': 'Information système',
                'verbose_name_plural': 'Informations système',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueMachine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_modification', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('changement_utilisateur', "Changement d'utilisateur"), ('changement_statut', 'Changement de statut'), ('maintenance', 'Maintenance'), ('synchronisation', 'Synchronisation')], max_length=30)),
                ('description', models.TextField()),
                ('donnees_avant', models.JSONField(blank=True, null=True)),
                ('donnees_apres', models.JSONField(blank=True, null=True)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='machines.machine')),
            ],
            options={
                'verbose_name': 'Historique machine',
                'verbose_name_plural': 'Historiques machines',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='LogicielInstalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('version', models.CharField(blank=True, max_length=100)),
                ('editeur', models.CharField(blank=True, max_length=100)),
                ('date_installation', models.DateTimeField(blank=True, null=True)),
                ('taille', models.BigIntegerField(blank=True, help_text='Taille en bytes', null=True)),
                ('licence_requise', models.BooleanField(default=False)),
                ('licence_valide', models.BooleanField(default=True)),
                ('autorise', models.BooleanField(default=True)),
                ('bloque', models.BooleanField(default=False)),
                ('date_detection', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_maj', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logiciels', to='machines.machine')),
            ],
            options={
                'verbose_name': 'Logiciel installé',
                'verbose_name_plural': 'Logiciels installés',
                'ordering': ['nom'],
                'unique_together': {('machine', 'nom', 'version')},
            },
        ),
        migrations.CreateModel(
            name='InterfaceReseau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_interface', models.CharField(choices=[('ethernet', 'Ethernet'), ('wifi', 'Wi-Fi'), ('bluetooth', 'Bluetooth'), ('vpn', 'VPN'), ('autre', 'Autre')], max_length=50)),
                ('adresse_mac', models.CharField(blank=True, max_length=17)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('masque_reseau', models.GenericIPAddressField(blank=True, null=True)),
                ('passerelle', models.GenericIPAddressField(blank=True, null=True)),
                ('dns_primaire', models.GenericIPAddressField(blank=True, null=True)),
                ('dns_secondaire', models.GenericIPAddressField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_derniere_maj', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces_reseau', to='machines.machine')),
            ],
            options={
                'verbose_name': 'Interface réseau',
                'verbose_name_plural': 'Interfaces réseau',
                'unique_together': {('machine', 'nom')},
            },
        ),
    ]
