# Generated by Django 5.1.5 on 2025-06-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_alter_machine_numero_inventaire_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogicielInstalle',
        ),
    ]
