# Generated by Django 5.1.5 on 2025-06-13 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_delete_logicielinstalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogicielInstalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('version', models.CharField(blank=True, max_length=100)),
                ('editeur', models.CharField(blank=True, max_length=100)),
                ('date_installation', models.DateTimeField(blank=True, null=True)),
                ('taille', models.BigIntegerField(blank=True, help_text='Taille en bytes', null=True)),
                ('licence_requise', models.BooleanField(default=False)),
                ('licence_valide', models.BooleanField(default=True)),
                ('autorise', models.BooleanField(default=True)),
                ('bloque', models.BooleanField(default=False)),
                ('date_detection', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_maj', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logiciels', to='machines.machine')),
            ],
            options={
                'verbose_name': 'Logiciel installé',
                'verbose_name_plural': 'Logiciels installés',
                'ordering': ['nom'],
                'unique_together': {('machine', 'nom', 'version')},
            },
        ),
    ]
