# Generated by Django 5.1.5 on 2025-06-16 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_logicielinstalle'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieLogiciel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('couleur', models.CharField(default='#007bff', help_text="Couleur hexadécimale pour l'affichage", max_length=7)),
                ('icone', models.CharField(blank=True, max_length=50)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie de logiciel',
                'verbose_name_plural': 'Catégories de logiciels',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='logicielinstalle',
            name='motif_blocage',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='LogicielReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('editeur', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('niveau_securite', models.CharField(choices=[('libre', 'Libre - Aucune restriction'), ('controle', 'Contrôlé - Autorisation requise'), ('restreint', 'Restreint - Utilisateurs spécifiques'), ('interdit', 'Interdit - Bloqué par défaut')], default='controle', max_length=20)),
                ('versions_autorisees', models.TextField(blank=True, help_text='Versions autorisées (une par ligne)')),
                ('versions_interdites', models.TextField(blank=True, help_text='Versions interdites (une par ligne)')),
                ('licence_requise', models.BooleanField(default=False)),
                ('type_licence', models.CharField(blank=True, max_length=100)),
                ('cout_licence', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.categorielogiciel')),
            ],
            options={
                'verbose_name': 'Logiciel de référence',
                'verbose_name_plural': 'Logiciels de référence',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='DemandeAutorisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logiciel_nom', models.CharField(help_text='Nom du logiciel demandé', max_length=200)),
                ('logiciel_version', models.CharField(blank=True, max_length=100)),
                ('logiciel_editeur', models.CharField(blank=True, max_length=100)),
                ('justification', models.TextField(help_text='Justification métier pour cette demande')),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('refuse', 'Refusé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('commentaire_admin', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_logiciels', to='machines.machine')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_logiciels', to=settings.AUTH_USER_MODEL)),
                ('logiciel_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.logicielreference')),
            ],
            options={
                'verbose_name': "Demande d'autorisation",
                'verbose_name_plural': "Demandes d'autorisations",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='logicielinstalle',
            name='logiciel_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.logicielreference'),
        ),
        migrations.CreateModel(
            name='AutorisationLogiciel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_autorisation', models.CharField(choices=[('utilisateur', 'Utilisateur spécifique'), ('groupe', "Groupe d'utilisateurs"), ('structure', 'Structure complète'), ('site', 'Site spécifique')], max_length=20)),
                ('statut', models.CharField(choices=[('autorise', 'Autorisé'), ('refuse', 'Refusé'), ('en_attente', 'En attente'), ('expire', 'Expiré')], default='autorise', max_length=20)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, help_text='Laisser vide pour une autorisation permanente', null=True)),
                ('versions_autorisees', models.TextField(blank=True, help_text='Versions spécifiquement autorisées (une par ligne)')),
                ('motif', models.TextField(blank=True, help_text="Motif de l'autorisation ou du refus")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('autorise_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorisations_accordees', to=settings.AUTH_USER_MODEL)),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autorisations_logiciels', to='users.groupe')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autorisations_logiciels', to='users.site')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autorisations_logiciels', to='users.structure')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autorisations_logiciels', to=settings.AUTH_USER_MODEL)),
                ('logiciel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorisations', to='machines.logicielreference')),
            ],
            options={
                'verbose_name': 'Autorisation logiciel',
                'verbose_name_plural': 'Autorisations logiciels',
                'ordering': ['-date_creation'],
                'unique_together': {('logiciel', 'groupe'), ('logiciel', 'site'), ('logiciel', 'structure'), ('logiciel', 'utilisateur')},
            },
        ),
    ]
