# Generated by Django 5.1.5 on 2025-06-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_categorielogiciel_logicielinstalle_motif_blocage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logicielreference',
            name='niveau_securite',
            field=models.CharField(choices=[('libre', 'Libre - Aucune restriction'), ('controle', 'Contrôlé - Autorisation requise'), ('restreint', 'Restreint - Utilisateurs spécifiques'), ('interdit', 'Interdit - Bloqué par défaut')], default='libre', max_length=20),
        ),
    ]
