# Generated by Django 5.1.5 on 2025-06-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_notificationticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='statut',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('assigne', 'Assigné'), ('en_cours', 'En cours'), ('en_attente', 'En attente'), ('resolu', 'Résolu'), ('ferme', 'Fermé'), ('rejete', 'Rejeté')], default='en_cours', max_length=20),
        ),
    ]
