# Generated by Django 5.1.5 on 2025-06-13 03:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, max_length=50)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Catégorie d'équipement",
                'verbose_name_plural': "Catégories d'équipements",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, unique=True)),
                ('numero_inventaire', models.CharField(max_length=50, unique=True)),
                ('code_barre', models.CharField(blank=True, max_length=100)),
                ('marque', models.CharField(blank=True, max_length=100)),
                ('modele', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('utilise', 'Utilisé'), ('maintenance', 'En maintenance'), ('hors_service', 'Hors service'), ('retire', 'Retiré')], default='disponible', max_length=20)),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_achat', models.DateField(blank=True, null=True)),
                ('fournisseur', models.CharField(blank=True, max_length=200)),
                ('date_fin_garantie', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.categorieequipement')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.site')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'ordering': ['nom'],
            },
        ),
    ]
