# Generated by Django 5.1.5 on 2025-06-16 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('machines', '0005_categorielogiciel_logicielinstalle_motif_blocage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorisationInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attribution', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('autorisation_logiciel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements_inventaire', to='machines.autorisationlogiciel')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorisations_logiciels', to='inventory.equipement')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Autorisation inventaire',
                'verbose_name_plural': 'Autorisations inventaire',
                'ordering': ['-date_attribution'],
                'unique_together': {('equipement', 'autorisation_logiciel')},
            },
        ),
    ]
