# Generated by Django 5.1.5 on 2025-06-13 12:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteSysteme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('niveau', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('critical', 'Critique')], max_length=20)),
                ('type_alerte', models.CharField(choices=[('system', 'Système'), ('network', 'Réseau'), ('security', 'Sécurité'), ('performance', 'Performance'), ('disk', 'Disque'), ('memory', 'Mémoire'), ('cpu', 'Processeur')], max_length=20)),
                ('resolu', models.BooleanField(default=False)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('valeur_seuil', models.FloatField(blank=True, null=True)),
                ('valeur_actuelle', models.FloatField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='machines.machine')),
                ('resolu_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_resolues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerte système',
                'verbose_name_plural': 'Alertes système',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RapportMonitoring',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('type_rapport', models.CharField(choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel')], max_length=20)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('machines_monitored', models.IntegerField(default=0)),
                ('alertes_generees', models.IntegerField(default=0)),
                ('temps_indisponibilite', models.DurationField(blank=True, null=True)),
                ('fichier_rapport', models.FileField(blank=True, null=True, upload_to='monitoring/reports/%Y/%m/')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('genere_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport de monitoring',
                'verbose_name_plural': 'Rapports de monitoring',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='StatusMachine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('online', 'En ligne'), ('offline', 'Hors ligne'), ('warning', 'Avertissement'), ('critical', 'Critique'), ('unknown', 'Inconnu')], default='unknown', max_length=20)),
                ('derniere_verification', models.DateTimeField(auto_now=True)),
                ('temps_reponse', models.FloatField(blank=True, help_text='Temps de réponse en ms', null=True)),
                ('cpu_usage', models.FloatField(blank=True, help_text='Utilisation CPU en %', null=True)),
                ('ram_usage', models.FloatField(blank=True, help_text='Utilisation RAM en %', null=True)),
                ('disk_usage', models.FloatField(blank=True, help_text='Utilisation disque en %', null=True)),
                ('ping_success', models.BooleanField(default=False)),
                ('last_ping_time', models.DateTimeField(blank=True, null=True)),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_monitoring', to='machines.machine')),
            ],
            options={
                'verbose_name': 'Statut de machine',
                'verbose_name_plural': 'Statuts de machines',
                'ordering': ['-derniere_verification'],
            },
        ),
        migrations.CreateModel(
            name='MetriquePerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpu_percent', models.FloatField(help_text='Utilisation CPU en %')),
                ('cpu_count', models.IntegerField(help_text='Nombre de cœurs CPU')),
                ('memory_total', models.BigIntegerField(help_text='Mémoire totale en bytes')),
                ('memory_used', models.BigIntegerField(help_text='Mémoire utilisée en bytes')),
                ('memory_percent', models.FloatField(help_text='Utilisation mémoire en %')),
                ('disk_total', models.BigIntegerField(help_text='Espace disque total en bytes')),
                ('disk_used', models.BigIntegerField(help_text='Espace disque utilisé en bytes')),
                ('disk_percent', models.FloatField(help_text='Utilisation disque en %')),
                ('network_bytes_sent', models.BigIntegerField(default=0)),
                ('network_bytes_recv', models.BigIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metriques', to='machines.machine')),
            ],
            options={
                'verbose_name': 'Métrique de performance',
                'verbose_name_plural': 'Métriques de performance',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['machine', '-timestamp'], name='monitoring__machine_2a4a9a_idx')],
            },
        ),
        migrations.CreateModel(
            name='SeuillAlerte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('metrique', models.CharField(choices=[('cpu', 'CPU'), ('memory', 'Mémoire'), ('disk', 'Disque'), ('network', 'Réseau'), ('ping', 'Ping')], max_length=20)),
                ('seuil_warning', models.FloatField(help_text="Seuil d'avertissement")),
                ('seuil_critical', models.FloatField(help_text='Seuil critique')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seuils_alerte', to='users.structure')),
            ],
            options={
                'verbose_name': "Seuil d'alerte",
                'verbose_name_plural': "Seuils d'alerte",
                'ordering': ['metrique'],
                'unique_together': {('metrique', 'structure')},
            },
        ),
    ]
