name: Build Android APK

on:
  push:
    branches: [ main ]
    paths: 
      - 'mobile_app/**'
      - '.github/workflows/build-android.yml'
  pull_request:
    branches: [ main ]
    paths: 
      - 'mobile_app/**'
  workflow_dispatch:  # Permet de déclencher manuellement

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache buildozer global directory
      uses: actions/cache@v3
      with:
        path: ~/.buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('mobile_app/buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-
    
    - name: Cache buildozer directory
      uses: actions/cache@v3
      with:
        path: mobile_app/.buildozer
        key: ${{ runner.os }}-buildozer-app-${{ hashFiles('mobile_app/buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-app-
    
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-8-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython
    
    - name: Build APK
      working-directory: mobile_app
      run: |
        buildozer android debug
    
    - name: Sign APK (if release)
      if: github.ref == 'refs/heads/main'
      working-directory: mobile_app
      run: |
        # Placeholder pour signature APK en production
        echo "APK built successfully"
    
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: ITSM-Companion-APK-${{ github.sha }}
        path: mobile_app/bin/*.apk
        retention-days: 30
    
    - name: Create Release (if tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: mobile_app/bin/*.apk
        draft: false
        prerelease: false