name: Desktop App Build

on:
  push:
    branches: [ main ]
    paths: 
      - 'desktop_app/**'
      - '.github/workflows/desktop-app.yml'
  pull_request:
    branches: [ main ]
    paths: 
      - 'desktop_app/**'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kivy kivymd pyinstaller
        pip install -r requirements.txt
    
    - name: Build Windows executable
      run: |
        cd desktop_app
        pyinstaller --onefile --windowed --name="ITSM-Desktop" main.py
    
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: ITSM-Desktop-Windows
        path: desktop_app/dist/ITSM-Desktop.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev build-essential libgl1-mesa-dev
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kivy kivymd pyinstaller
        pip install -r requirements.txt
    
    - name: Build Linux executable
      run: |
        cd desktop_app
        pyinstaller --onefile --name="ITSM-Desktop" main.py
    
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: ITSM-Desktop-Linux
        path: desktop_app/dist/ITSM-Desktop